# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/ptex/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/ptex/src/doc/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/ptex/src/ptex/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/ptex/src/tests/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/ptex/src/utils/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/CTest.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/CTestTargets.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/CTestUseLaunchers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/DartConfiguration.tcl.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/FindDoxygen.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/FindZLIB.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/GNUInstallDirs.cmake))

/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.24.2/bin/cmake -H/Users/brendanmulcahey/Documents/pbrt-v3_2023 -B/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds
