# CMake generated Testfile for 
# Source directory: /Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog
# Build directory: /Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(demangle "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/Debug/demangle_unittest")
  set_tests_properties(demangle PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;530;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(demangle "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/Release/demangle_unittest")
  set_tests_properties(demangle PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;530;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(demangle "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/MinSizeRel/demangle_unittest")
  set_tests_properties(demangle PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;530;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(demangle "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/RelWithDebInfo/demangle_unittest")
  set_tests_properties(demangle PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;530;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
else()
  add_test(demangle NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(logging "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/Debug/logging_unittest")
  set_tests_properties(logging PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;531;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(logging "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/Release/logging_unittest")
  set_tests_properties(logging PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;531;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(logging "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/MinSizeRel/logging_unittest")
  set_tests_properties(logging PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;531;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(logging "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/RelWithDebInfo/logging_unittest")
  set_tests_properties(logging PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;531;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
else()
  add_test(logging NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(signalhandler "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/Debug/signalhandler_unittest")
  set_tests_properties(signalhandler PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;534;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(signalhandler "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/Release/signalhandler_unittest")
  set_tests_properties(signalhandler PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;534;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(signalhandler "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/MinSizeRel/signalhandler_unittest")
  set_tests_properties(signalhandler PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;534;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(signalhandler "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/RelWithDebInfo/signalhandler_unittest")
  set_tests_properties(signalhandler PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;534;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
else()
  add_test(signalhandler NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(stacktrace "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/Debug/stacktrace_unittest")
  set_tests_properties(stacktrace PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;538;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(stacktrace "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/Release/stacktrace_unittest")
  set_tests_properties(stacktrace PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;538;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(stacktrace "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/MinSizeRel/stacktrace_unittest")
  set_tests_properties(stacktrace PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;538;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(stacktrace "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/RelWithDebInfo/stacktrace_unittest")
  set_tests_properties(stacktrace PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;538;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
else()
  add_test(stacktrace NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(stl_logging "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/Debug/stl_logging_unittest")
  set_tests_properties(stl_logging PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;541;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(stl_logging "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/Release/stl_logging_unittest")
  set_tests_properties(stl_logging PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;541;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(stl_logging "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/MinSizeRel/stl_logging_unittest")
  set_tests_properties(stl_logging PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;541;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(stl_logging "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/RelWithDebInfo/stl_logging_unittest")
  set_tests_properties(stl_logging PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;541;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
else()
  add_test(stl_logging NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(symbolize "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/Debug/symbolize_unittest")
  set_tests_properties(symbolize PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;544;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(symbolize "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/Release/symbolize_unittest")
  set_tests_properties(symbolize PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;544;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(symbolize "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/MinSizeRel/symbolize_unittest")
  set_tests_properties(symbolize PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;544;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(symbolize "/Users/brendanmulcahey/Documents/pbrt-v3_2023/myBuilds/src/ext/glog/RelWithDebInfo/symbolize_unittest")
  set_tests_properties(symbolize PROPERTIES  _BACKTRACE_TRIPLES "/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;544;add_test;/Users/brendanmulcahey/Documents/pbrt-v3_2023/src/ext/glog/CMakeLists.txt;0;")
else()
  add_test(symbolize NOT_AVAILABLE)
endif()
